"""Added company active / inactive toggle

Revision ID: 088d905213ae
Revises: e2a0139cb6ef
Create Date: 2024-10-05 16:36:14.651764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088d905213ae'
down_revision = 'e2a0139cb6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
