"""empty message

Revision ID: 101330f831b9
Revises: a4be23161de7
Create Date: 2024-08-28 22:37:33.894690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101330f831b9'
down_revision = 'a4be23161de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.String(length=1064), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=True)

    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_name'), ['name'], unique=True)

    op.create_table('assignee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignee_destination_city'), ['destination_city'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignee_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignee_origin_country'), ['origin_country'], unique=False)

    op.create_table('company_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignee_package',
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['assignee.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignee_package')
    op.drop_table('company_package')
    with op.batch_alter_table('assignee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignee_origin_country'))
        batch_op.drop_index(batch_op.f('ix_assignee_name'))
        batch_op.drop_index(batch_op.f('ix_assignee_destination_city'))

    op.drop_table('assignee')
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_name'))

    op.drop_table('package')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_name'))

    op.drop_table('company')
    # ### end Alembic commands ###
