"""Updated Assignee model to accept date objects, rather than times

Revision ID: 8c5c11905e24
Revises: 492e1e458938
Create Date: 2024-10-05 17:52:20.394896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5c11905e24'
down_revision = '492e1e458938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignee', schema=None) as batch_op:
        batch_op.alter_column('nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('booking_date',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('arrival_date',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('work_start_date',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('temp_flat',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('spouse',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('child',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('pets',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('hub',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('hr_contact',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignee', schema=None) as batch_op:
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('hr_contact',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('hub',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('pets',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('child',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('spouse',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('temp_flat',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('work_start_date',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('arrival_date',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('booking_date',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
