"""empty message

Revision ID: 9d24dd0ce46b
Revises: 301f41697cf8
Create Date: 2024-09-23 20:50:58.904202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d24dd0ce46b'
down_revision = '301f41697cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address1', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('address2', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('postcode')
        batch_op.drop_column('address2')
        batch_op.drop_column('address1')

    # ### end Alembic commands ###
