"""as above

Revision ID: b44049159cf9
Revises: fadb0b503700
Create Date: 2024-09-25 14:47:01.411967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44049159cf9'
down_revision = 'fadb0b503700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_company')
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('default_price')

    op.create_table('_alembic_tmp_company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=256), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1064), nullable=True),
    sa.Column('address1', sa.VARCHAR(length=64), nullable=True),
    sa.Column('address2', sa.VARCHAR(length=64), nullable=False),
    sa.Column('postcode', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
