"""added default price to packages

Revision ID: fadb0b503700
Revises: 9d24dd0ce46b
Create Date: 2024-09-25 14:41:33.977649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadb0b503700'
down_revision = '9d24dd0ce46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('address2',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('postcode',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('default_price')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('postcode',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address2',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
